### ISSUE TITLE
'No podcast playing'

### ISSUE THREAD

**Issue by stevelitchfield** [kypeli/Podcatcher#21]
Start a podcast playing and then pause it.
Let the screen timeout.
Wake the screen and dismiss the lock shade. 
'No podcast playing'. 8-(

OK (I think), press 'back'.
'Play history' is blank. 8-(

Switching away and then restarting Podcatcher restores the 'Play history'.

All on Lumia 920.

**Comment by stevelitchfield** [comment]
Curiously, although the 'No podcast playing' always occurs, the blank play history seems to depend up on where the podcast playback was started in the UI. Most of the time, play history IS there. I'll try and spot a pattern!

**Comment by kypeli** [comment]
I brief update and comment about this; it does seem that the player is actually dismissed and killed by the Windows Phone platform if the screen locks while the player is paused. Then when screenlock is dismissed, it's actually correct behavior to show "No podcast playing" because the player has been killed by Windows Phone. This can be observed by the fact that there are no screenlock controls to be seen anymore. 

So I am coming to the conclusion that this is correct behavior and I cannot do anything about the killing of the player in this case...

**Comment by kypeli** [comment]
Open after Steve's mail :)

**Comment by kypeli** [comment]
This bug is not valid anymore with the new player approach in the next version. 

Happy to close :)
