### ISSUE TITLE
Erratic UI behaviour on resumption of playback

### ISSUE THREAD

**Issue by stevelitchfield** [kypeli/Podcatcher#25]
Start the phone from scratch. Start Podcatcher. Look in play history and tap to resume something.

Sometimes the UI gets dismissed and the phone's Start screen appears (though with the podcast playing successfully)

Sometimes the player window comes up as normal.

And I haven't been able to spot a pattern yet. Very odd.

**Comment by kypeli** [comment]
This is unfortunately a known issue and can also happen when tapping on some subscription in the main list. This is due to Windows Phone's thread unsafe access to the LINQ-to-SQL database. I've tried to eliminate this all together, but I feel it's something I don't grok or it's a bigger change to remove this issue altogether. 

And yes, this happens totally randomly - basically if you happen to access the podcast subscription at the same time as then it is being updated.

This issue drives me nuts as well and I really want to come up with a way to fix this...

**Comment by kypeli** [comment]
This is fixed in version 2.2.1.0
