### ISSUE TITLE
Deleting buffer data

### ISSUE THREAD

**Issue by lemixtape** [kypeli/Podcatcher#28]
I stream all of my podcasts (audio and video). From what I have seen, Podcatcher buffers the  podcasts which is perfect but when and how is Podcatcher deleting the buffer data? As I only have 16GB on my device (HTC 8X), I often get the Low Space alert when I stream an episode. Since I cannot quit the app, do I have to restart the phone to erase the buffer data?

**Comment by kypeli** [comment]
For streaming I 100% rely on Windows Phone platform components, which take care of fetching, buffering and showing/playing. So unfortunately I cannot answer this question in more detail now (maybe there's some docs somewhere...) as this is probably more a Microsoft internal thing. 

One place to try to find out about this kind of things is of course Microsoft's discussion board at http://social.msdn.microsoft.com/Forums/en-US/wpdevelop/threads. Sometimes Microsoft answers a question, sometimes they don't.

Closing because there's not much Podcatcher can do with this thing.
